title: Kanona Events
description: Premium corporate event planning and strategy
theme: minima
baseurl: "/kanona-events"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
